POST http://localhost:3000/consumo-energia HTTP/1.1
content-type: application/json

{
    "userId": 123,
    "consumo": 100,
    "data": "2025-05-01"
    
}

###
POST http://localhost:3000/consumo-energia HTTP/1.1
content-type: application/json

{
   "userId": 123,
    "consumo": 200,
    "data": "2025-06-01"
}

###
POST http://localhost:3000/consumo-energia HTTP/1.1
content-type: application/json

{
   "userId": 123,
    "consumo": 500,
    "data": "2025-04-01"
}

###
GET http://localhost:3000/consumo-energia/historico?userId=123&dataInicio=2025-04-01&dataFim=2025-06-31 HTTP/1.1


###
GET http://localhost:3000/consumo-energia/alertas?userId=123&data=2025-06-01 HTTP/1.1

